### ISSUE TITLE
Not all providers expose agents

### ISSUE THREAD

**Issue by MioQuispe** [dfinity/ic-js#216]
Hey all I took a quick look at the package, and it looks great.
It would be great if it could support all wallets/idps however, I noticed it expects you to pass in an agent when creating the canisters.
From developing connect2ic I learned the only common interface they have is:      provider.createActor(canisterId, idl) -> actor

So how about taking the actor as an argument instead of an agent? or providing it as an option

**Comment by peterpeterparker** [comment]
The `agent` is optional. If you do not pass one a default will be used or can you point me to the method you noticed that requires it?

We use an optional `agent` as argument because the idea of the library is to make it easy to query the governance, ledger etc. backend canisters. If we would use an `actor` as argument it would mean that the developer would have to create it on his/her side, which implies that the developer would have to set up candid files etc. as well.

By obfuscating the actors in the library, we also take care of initializing these with the most recent candid files that always match the current version of the governance, ledger etc. canisters on mainnet. So that the developer by using the lib do not have to worry if there was or not breaking changes.

For these reason, and also because it would be a big breaking changes for NNS-dapp, I would rather like not to use an actor instead of the agent.

Being said and as you suggested, if you have a use case in which an optional `actor` would make sense, not against adding it. Can you share a bit more details about your example?

**Comment by MioQuispe** [comment]
> The `agent` is optional. If you do not pass one a default will be used or can you point me to the method you noticed that requires it?
> 
> We use an optional `agent` as argument because the idea of the library is to make it easy to query the governance, ledger etc. backend canisters. If we would use an `actor` as main argument it would mean that the developer would have to create it on his/her side, which implies that the developer would have to set up candid files etc. as well.
> 
> By obfuscating the actors in the library, we also take care of initializing these with the most recent candid files that always match the current version of the governance, ledger etc. canisters on mainnet. So that the developer by using the lib do not have to worry if there was or not breaking changes.
> 
> For these reason, and also because it would be a big breaking changes for NNS-dapp, I would rather like not to use an actor instead of the agent.
> 
> ~Being said and as you suggested, if you have a use case in which an optional `actor` would make sense, not against adding it. Can you share a bit more details about your example?~
> 
> update:
> 
> Being said, you can already pass a particular actor for most features I think. For such purpose the `serviceOverride` and `certifiedServiceOverride` parameters can be used. Would that fit your use case?

Yeah that looks like it will work. I was looking at the SNS canisters so I didnt see it there. I guess its not implemented for all canisters?

**Comment by peterpeterparker** [comment]
> Yeah that looks like it will work. I was looking at the SNS canisters so I didnt see it there. I guess its not implemented for all canisters?

Yes.

The `SnsWrapper` does not but separatly all canisters (`SnsSwapCanister`, `SnsRootCanister`, `SnsLedgerCanister` and `SnsGovernanceCanister`) classes have the `service, certifiedService` - `ActorSubclass` - as options.

Here again the idea is to have a `SnsWrapper` that offers the most "simple" solution and provide separate classes for more detailed usage.

Would that work for your use case?

**Comment by MioQuispe** [comment]
> > Yeah that looks like it will work. I was looking at the SNS canisters so I didnt see it there. I guess its not implemented for all canisters?
> 
> Yes.
> 
> The `SnsWrapper` does not but separatly all canisters (`SnsSwapCanister`, `SnsRootCanister`, `SnsLedgerCanister` and `SnsGovernanceCanister`) classes have the `service, certifiedService` - `ActorSubclass` - as options.
> 
> Here again the idea is to have a `SnsWrapper` that offers the most "simple" solution and provide separate classes for more detailed usage.
> 
> Would that work for your use case?

Oh okay, I might have missed it then. That should work yeah, thanks. ill reopen if theres any issue.

**Comment by peterpeterparker** [comment]
Let me know if it works out and sure reopen it if it does not!

We have documented (can be still improved) the functions but, we still hope to find time someday to blog some examples of the lib usage. It would make more easy to grasp what it can offer.
