### ISSUE TITLE
Using @dfinity/nns throw webpack error, optional chain is not support. Webpack5 is ok.

### ISSUE THREAD

**Issue by honopu** [dfinity/ic-js#252]
To make it more convenient for users,  i think a lower EcmaScript target is better

**Comment by peterpeterparker** [comment]
In this particular error case, Webpack 5 - which introduces the support for optional chaining - has been released more than 2 years ago.

When it comes ot the JS standard, if I am not wrong, optional chaining has been introduced in es6 and is supported in all major browser since few years.

Therefore I think the complexity of supporting and maintaining older EcmaScript target and the extra work it adds should not be supported by this library.
